### ISSUE TITLE
PfGridview Cell sizes

### ISSUE THREAD

**Issue by sham021** [pettyfun/pf-gridview#10]
Im trying to create a grid like this this app: http://a603.phobos.apple.com/us/r1000/077/Purple/v4/87/df/c2/87dfc2f5-99d3-c8fc-5e08-60b3f677e2ec/mzl.kvwmkpcc.320x480-75.jpg

My problem is that i can only set the size for cell just once, which makes each cell the same size, i need it so that i can set the sizes for each cell (So some cells are bigger then others, like the Sky app in the link above)

Please someone help, i have spent hours without any luck, no matter what i try it doesn't work

Thanks in advance :)

**Comment by yjpark** [comment]
In PFGridViewSection+Internal.m, `- (CGRect)frameForCol:(NSUInteger)col inRow:(NSUInteger)row` is used to calculate the frame for each cell, and which is used in many other place for the logic to arrange the cells.

For your needs, don't think there is a easy way to tweak a grid view. Probably it's better to create your own widget for it.

If the rows are not too long, a simple solution is to create a normal table view, in which each row is a long row, then you just arrange the "columns" in each row, and synchronize the scroll position for visible rows.

Maybe a pinterest like component can help you? a quick search leads:
- https://github.com/ptshih/PSCollectionView
- http://www.binpress.com/app/pinterest-gridview-for-ios-masonryview/836

**Comment by sham021** [comment]
ok thanks for that, i will try your solution out, hopefully it all works out..

Thanks again :+1:

**Comment by sham021** [comment]
Hi, i got a new gridview that can resize each cell, can you please tell me how you have done the scrolling in pfgridview?, like having the left side not scroll when scrolling horizontally and the header not scroll when scrolling vertically?

in the new gridview that im using, it has a header, side and then the gidview inside, i have setup scrolling but it's not working like your one, so can you please help me, thanks.
